### ISSUE TITLE
Allow configurable inbound ports

### ISSUE THREAD

**Issue by zer0stars** [streamr-dev/network#1087]
Today, it is not possible to configure the inbound port range. Requesting a feature to specify the port range via config for running in cloud environments where only certain ports may be allowed.

**Comment by fonty1** [comment]
Done in `v8.0.4` by adding something like this to the broker config,
```
{
  ...
  "client": {
    ...
    "network": {
      ...
      "webrtcPortRange": {
		  min: 1337,
		  max: 1500,
	  }
    }
}
```
