### ISSUE TITLE
missing LICENSE file in repo root

### ISSUE THREAD

**Issue by nupam** [streamr-dev/network#1762]
The streamr community should vote for what license to release the code with their tokens. Be it one of the GPL versions or even commercial.

#governance

**Comment by nupam** [comment]
@fonty1

**Comment by fonty1** [comment]
> The streamr community should vote for what license to release the code with their tokens. Be it one of the GPL versions or even commercial.
> 
> #governance

Thanks - acknowledged and will look into it!
