### ISSUE TITLE
Question - Does installation need XCode?

### ISSUE THREAD

**Issue by newbreedofgeek** [streamr-dev/network#181]
I cant seem to install your streamr-client module.

- I'm on a MAC
- I've got `v16.8.0`
- I run `npm install streamr-client`

It throws this error.
```
...
npm ERR! gyp: No Xcode or CLT version detected!
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
...
```

Is Xcode a requirement for this to work?

**Comment by kare** [comment]
You can install macOS Command Line Tools. Whole Xcode installation isn't required.
