### ISSUE TITLE
client.getOrCreateStream() does not create the stream. 

### ISSUE THREAD

**Issue by oharkins** [streamr-dev/network#331]
This function does not seem to create the stream, it fails with: ```
NotFoundError: NOT_FOUND: Stream: name=0xRedacted/readings/A8404139318229B5
    at StreamEndpoints.getStreamByName (/Users/redacted/Documents/streamr/Streamr_Docker/node_modules/streamr-client/src/rest/StreamEndpoints.js:97:85)
```
I expect it to not find the stream however I do expect that function to create the stream object if it does not exist. 

Thanks

**Comment by oharkins** [comment]
update to this it does work when awaited not when using .then()

**Comment by fonty1** [comment]
@oharkins - was this solved in Discord? I did do a test of this flow and it seemed to work - does your stream appear in the [Core app](https://streamr.network/core/streams)?
