### ISSUE TITLE
WebRTC-private-addresses 

### ISSUE THREAD

**Issue by spocthier83** [streamr-dev/network#474]
Hello, 

When following this procedure (because i have the warning) :
https://github.com/streamr-dev/network-monorepo/wiki/WebRTC-private-addresses

I have this error : 
> Error: must NOT have additional properties (network)

Thanks in advance!

**Comment by juslesan** [comment]
Hi, if you are running a broker node you should insert this part of the configuration inside the client-object like so:

```
{
  "client": {
      ...
      "network": {
           "webrtcDisallowPrivateAddresses": true          
      }
   }
   ...
}
```

**Comment by radoeka** [comment]
Why not include the setting by default (but then set to false)?
It's way easier to set it to true in this way.
It could even include the explanation.

**Comment by juslesan** [comment]
> Why not include the setting by default (but then set to false)?

This is something that has been discussed and is likely to make it in to the next release.

**Comment by juslesan** [comment]
#483
